# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:

  buildPackage:
    runs-on: ubuntu-latest
    env:
      CI_BUILD: 'true'
    steps:
    - uses: actions/checkout@v2
    - run:
        npm i --save-dev
    - name:  'Automated Version Bump'
      uses:  'phips28/gh-action-bump-version@master'
      if: github.event_name == 'push'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PACKAGEJSON_DIR:  ''
    - run:
        npm run build
    - uses: actions/setup-node@v2
      with:
        registry-url: 'https://npm.pkg.github.com'
    - name: Publish package
      if: github.event_name == 'push'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:
        npm publish

  triggerUpdate:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [buildPackage]
    env:
      RELEASE_TYPE: testing

    steps:
      - name: Set release type
        run: echo "RELEASE_TYPE=stable" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/master'

      - name: Trigger update build
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.STE_APP_BUILD_TOKEN }}" --data '{"event_type": "build", "client_payload": { "release": "${{ env.RELEASE_TYPE }}", "bump": "patch"}}' https://api.github.com/repos/stereotech/STE-App-Build/dispatches
